version: '3.1'

services:

  db:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d
      - ${MYSQL_VOLUME}:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci